### ISSUE TITLE
Failed to play video within web

### ISSUE THREAD

**Issue by fragilember** [GooglyBlox/free-numerade-videos#1]
Hi, I've been using this quite a while now and didn't really have issues. But recently, no link that I've tried work. Is this just how it is with some links and others may still play correctly?

Links I've tried:
1. https://www.numerade.com/ask/question/when-the-length-of-the-spring-in-example-83-changes-from-an-initial-value-of-220-cm-to-a-final-value-the-elastic-potential-energy-it-contributes-changes-by-find-the-final-length-24487/
2. https://www.numerade.com/ask/question/a-proton-has-speed-5x-10-ms-and-is-moving-in-a-circle-in-the-xy-plane-of-radius-r0175-mwhat-is-its-position-in-the-xy-plane-at-time-2010-200nsat0the-position-of-the-proton-is-0175m-and-it-ci-79773/

Thank you for your time.

**Comment by GooglyBlox** [comment]
Huh, strange! Both of those links seem to work for me. Are you using the [latest version of the userscript](https://github.com/GooglyBlox/free-numerade-videos/raw/refs/heads/main/userscript/numerade-video-viewer.user.js)?

**Comment by GooglyBlox** [comment]
It's been a couple weeks now so I'm going to close this issue and assume it was a version error - but if the issue persists and you still can't get it to work, please feel free to reopen this issue!
