### ISSUE TITLE
Not sure what the problem is 

### ISSUE THREAD

**Issue by aidanahram** [GooglyBlox/free-numerade-videos#2]
https://www.numerade.com/questions/suppose-a-in-mathbfrn-times-n-and-doperatornamediagleftd_1-ldots-d_nright-in-mathbfrn-times-n-show-h/?srsltid=AfmBOoqkbV5_PGwcjBnAKK51HNWevIa87jQswQEFyJIWqMYkWfRAbrWL

^ Doesn't work for this link.

**Comment by GooglyBlox** [comment]
Can reproduce! It looks like Numerade patched the script, I'll work to get it functioning again ASAP :)

**Comment by aidanahram** [comment]
Not sure exactly but seems to me that it is coming from the checkResourceExists() functions. 
Does it have something to do with the urls you're generating.
Thanks for responding so quick, I'm trying to work on it too. I can't find on the numerade page where the url would even be

**Comment by GooglyBlox** [comment]
Hm, this seems to be a larger issue than I thought it was. Typically they just scramble their DOM to make the script be unable to find the necessary elements, but this time it looks like they actually added proper auth to their CDN. If this is the case, then fixing it is borderline impossible. 

Here's a URL that used to work before: https://cdn.numerade.com/encoded/174d67da-b5af-4382-beab-1cd20862c358.webm
Before, there was no auth check on their CDN URLs. Having the URL meant you could access the file. Now, it throws the below error:
```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script/>
<Code>MissingKey</Code>
<Message>Missing Key-Pair-Id query parameter or cookie value</Message>
</Error>
```

From what I can assume, the error suggests the videos are now protected with CloudFront signed URLs, which require a Key-Pair-Id and signature. If that's the case, the user needs to be properly authenticated before accessing the CDN, which means my method is pretty much kaput. I'll take a look at it for a little while longer, but I'm not particularly hopeful about it.

**Comment by GooglyBlox** [comment]
Looks like I was right, CloudFront signing seems to be the case. The method I use for this script is definitely unusable now. 

There's potential for handling this how [lucida](https://www.npmjs.com/package/lucida) handles it, where you use premium accounts to serve the content to users, but unfortunately, I don't think Numerade is so big of a platform that people would donate their paid accounts to help non-paying users.

I'll archive this repository for now, but if anyone at any point donates me a premium account to run some tests, I might be able to revive the project!
